services:
  # A Docker web service
  - type: web
    env: docker
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: master # optional (defaults to master)
    dockerCommand: python3 main.py # optional (defaults to Dockerfile command)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
 
  